### ISSUE TITLE
BUG - [Expression to the left of comparison must be parenthesized at]

### ISSUE THREAD

**Issue by yedynaki** [fivetran/dbt_salesforce_formula_utils#26]
**Are you a current Fivetran customer?** 

Ihor Yedynak, Data Architect, Collegis Education

**Describe the bug**

I am getting the message below after setup and running model
{{ salesforce_formula_utils.sfdc_formula_view('enrollmentrx_rx_enrollment_opportunity_c') }}
Server error: Database Error in rpc request (from remote system)
Syntax error: Expression to the left of comparison must be parenthesized at [539:42]

**Steps to reproduce**
Add info to packages.yml file 
  - package: fivetran/salesforce_formula_utils
    version: [">=0.4.0", "<0.5.0"]
    # <see https://github.com/fivetran/dbt_salesforce_formula_utils/releases> for the latest versions
Execute dbt deps
Configure source.yml file
Execute dbt run --models myModel
![image](https://user-images.githubusercontent.com/64605598/136465305-962ffdf8-39b1-49d2-a309-a26887e3bae9.png)

Watch it fail 👀 haha

**Expected behavior**

**Project variables configuration**

```yml
copy dbt_project.yml here
```

**Package Version**

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.3

  - package: calogica/dbt_expectations
    version: 0.4.2
    # <see https://github.com/calogica/dbt-expectations/releases/latest> for the latest version tag

  - package: fivetran/salesforce_formula_utils
    version: [">=0.4.0", "<0.5.0"]
    # <see https://github.com/fivetran/dbt_salesforce_formula_utils/releases> for the latest versions
```

**Warehouse**

 
- [X] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
