### ISSUE TITLE
BUG - Resolve Mixed Casing Issues

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_salesforce_formula_utils#31]
**Are you a current Fivetran customer?** 

Fivetran created PR, but identified first by @morgankrey-amplitude

**Describe the bug**

The bug is well defined in [dbt-labs/dbt-utils#424](https://github.com/dbt-labs/dbt-utils/issues/424). Additionally the mentioned issue identifies the possible solution as well.

**Expected behavior**

Users with Mixed Casing in their Snowflake warehouse do not experience any dbt compilation issues.

**Package Version**

```yml
packages:
  - package: fivetran/salesforce_formula_utils
    version: [">=0.5.0", "<0.6.0"]
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [X] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)
