### ISSUE TITLE
full_statement_version=true does not produce fully qualified table names, required for Snowflake

### ISSUE THREAD

**Issue by jeff-skoldberg** [fivetran/dbt_salesforce_formula_utils#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Consider a source.yml like this:
```
  - name: salesforce
    database: fivetran
    schema: my_fivetran_salesforce_schema
    tables:
      - name: my_salesforce_table
      - name: fivetran_formula_model
      - name: fivetran_formula
```
And a connection in dbt Cloud with a default database of `my_default_database` 

Then I have a model, call it my_salesforce_table_with_formulas.sql, which contains this code:
`{{ salesforce_formula_utils.sfdc_formula_view(source_table='my_salesforce_table', full_statement_version=true) }}`

When I compile the SQL, I will find a `FROM` clause that contains a table that is not fully qualified:
```
from
my_fivetran_salesforce_schema.my_salesforce_table
```
When I try to preview the model or `dbt run` I will get this error:
`SQL compilation error: Schema 'MY_DEFAULT_DATABASE.MY_FIVETRAN_SALESFORCE_SCHEMA' does not exist or not authorized.`  (I'm on Snowflake, so upper case names)

It should of course by looking for `fivetran.my_fivetran_salesforce_schema`

### Expected behavior

The sql produced by the macro should be fully qualified with db name.  In this example:
```
from
fivetran.my_fivetran_salesforce_schema.my_salesforce_table
```

### dbt Project configurations

relevant config is in description of file.

### Package versions

packages:
  - package: fivetran/salesforce_formula_utils
    version: [">=0.7.0", "<0.8.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.2

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
